const enums = {
  ORDER_SECTION: 'ORDER_SECTION',
  CUSTOMER_DETAILS: 'CUSTOMER_SECTION',
  PAYMENT:'PAYMENT',
  PAYMENT_SUCCESSFUL: 'PAYMENT_SUCCESSFUL',
  PAYMENT_FAILED:'PAYMENT_FAILED'
}

module.exports = {enums};